apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.name}}
  namespace: default
  labels:
    app: {{.name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: {{.name}}
      qcloud-app: {{.name}}
  template:
    metadata:
      labels:
        k8s-app: {{.name}}
        qcloud-app: {{.name}}
    spec:
      containers:
      - env:
        - name: PASSWORD
          value: "{{.password}}"
        image: ccr.ccs.tencentyun.com/code-server/csc3050:v1.3
        imagePullPolicy: Always
        name: {{.name}}
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: 250m
            memory: 256Mi
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: qcloudregistrykey