apiVersion: v1
kind: Service
metadata:
  name: {{.name}}
  namespace: default
spec:
  ports:
    - name: 3049-3049-tcp
      port: 3049
      protocol: TCP
      targetPort: 3049
  selector:
    k8s-app: {{.name}}
    qcloud-app: {{.name}}
  type: LoadBalancer